// ng-remote-two/src/app/components/counter-button/counter-button.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'ui-ng-remote-two-counter-button',
  templateUrl: './counter-button.component.html',
  standalone: true,
  imports: [CommonModule],
})
export class CounterButtonComponent {
  count = 0;
  setCount(val: number) {
    this.count = val;
  }
}

<div class="flex flex-col items-center flex-grow h-full justify-around">
  <h1>Counter button</h1>
  <button
    class="border-2 border-sky-500 px-2 py-1"
    (click)="setCount(count + 1)"
  >
    count is {{ count }}
  </button>
  <span>this is a component from angular remote</span>
</div>

// host-react/src/components/CounterButton.tsx
import { useState } from "react";

function CounterButton() {
  const [count, setCount] = useState(0);
  return (
    <div className="flex flex-col items-center flex-grow h-full justify-around">
      <h1>Counter button</h1>
      <button className="border-2 border-sky-500 px-2 py-1" onClick={() => setCount((count) => count + 1)}>
        count is {count}
      </button>
      <span>this is a component from react-host</span>
    </div>
  );
}

export default CounterButton;
