// host-react/src/App.tsx
// import { useState } from 'react'
import {
  // createBrowserRouter,
  // RouterProvider,
  Outlet,
  Link,
} from "react-router-dom";
function App() {
  // const [count, setCount] = useState(0)
  const name = "React Host ";

  return (
    <div className="mt-8 p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg space-x-4 text-center">
      <p className="text-xl">
        <Link to={"/"}>MFE {name}</Link>
      </p>
      <hr className="mt-8" />
      <div className="mt-8">
        <Link to={"my-button"} className="p-6 hover:text-blue-600">
          Button
        </Link>
        <Link to={"angular-mfe"} className="p-6 hover:text-blue-600">
          Angular MFE
        </Link>
      </div>
      <hr className="mt-8" />
      <div className="h-96 flex flex-row justify-evenly align-middle">
        <Outlet />
      </div>
    </div>
  );
}

export default App;
{
  /* <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button> */
}

// ng-remote-two/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
    
@Component({
  selector: 'ui-ng-remote-two-root',
  templateUrl: './app.component.html',
  styles: [
    `@tailwind base;
    @tailwind components;
    @tailwind utilities;
    `
  ],
  standalone: true,
  imports: [
    RouterModule,
    CommonModule
  ]
})
export class AppComponent {
  title = 'ng-remote-two';
}

<div
  class="mt-8 p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg space-x-4 text-center"
>
  <p class="text-xl">
    <a routerLink="./">
      {{ title }}
    </a>
  </p>
  <hr class="mt-8" />
  <div class="mt-8">
    <a class="p-6 hover:text-blue-600" routerLink="./counter">Counter</a>
    <a class="p-6 hover:text-blue-600" routerLink="./contact">Contact</a>
  </div>
  <hr class="mt-8" />
  <div className="h-96 flex flex-row justify-evenly align-middle">
    <router-outlet></router-outlet>
  </div>
</div>
